### ISSUE TITLE
Context logger deadlock

### ISSUE THREAD

**Issue by IIITanbI** [VIP-Logic/NBomber#519]
When using the context logger, a deadlock occurs after a few seconds. In this example, a deadlock occurs after 1 or 2 seconds.
CPU I7-11390H

Link to full example: [https://github.com/IIITanbI/NBomberLoggerDeadlock](https://github.com/IIITanbI/NBomberLoggerDeadlock)

```csharp
using NBomber.CSharp;

namespace CSharpProd.HTTP;

internal class Program
{
    static void Main(string[] args)
    {
        var scenario = Scenario.Create("scenario", async context =>
        {
            var logger = context.Logger;

            logger.Information("Before request");
            await Task.Delay(500);
            logger.Information("After request");

            return Response.Ok();
        })
        .WithoutWarmUp()
        .WithLoadSimulations(Simulation.Inject(rate: 1000, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(5)));

        NBomberRunner
            .RegisterScenarios(scenario)
            .Run();
    }
}
```

Use package 
```csharp
<PackageReference Include="NBomber" Version="4.0.0-rc" />
```

**Comment by AntyaDev** [comment]
@IIITanbI  thanks
will take a look

**Comment by AntyaDev** [comment]
Hi @IIITanbI 
From what I see:
It is something related to Serilog itself because when you do: logger.Debug() nothing happens.

I think it's something related to https://spectreconsole.net/live/live-display
Because when I disable rendering of this live table, I see no deadlocks too.

I will need some time to decide how to fix it.
