### ISSUE TITLE
[Cluster] Coordinator should wait forever when MinAgentsCount is specified but not satisfied

### ISSUE THREAD

**Issue by mklpanasiuk** [VIP-Logic/NBomber#522]
In Kubernetes cluster, there is a case when the NBomber coordinator may start first and after some period of time start agents. The period of starting agents may vary from 30 seconds up to 10 minutes, it depends on the Kube cluster autoscale policy. 
NBomber v4 proposes to use MinAgentsCount to start test, but it waits around 1 minute. This time is too short for us. Please add parameters for the NBomer runner (coordinator) to wait for agents, e.g., WaitAgentsTimeout.
So the tandem of MinAgentsCount and WaitAgentsTimeout would be ideal for everybody I guess.

**Comment by AntyaDev** [comment]
I thought about this problem and realized that it should be done more simpler. 
Instead of giving all these configurations to the user, I would love to avoid mentioning them.
I want to abstract from the user as much as possible and provide the cloud experience.

I think that if a **MinAgentCount** is specified, then Coordinator should retry until the cluster reaches MinAgentCount. In this case, the user doesn't need to know and configure such settings.

What do you think about such simplification?

**Comment by mklpanasiuk** [comment]
Agree with you. So just to finalize if MinAgentCount is set then the test starts only when the agents count is enough without a timeout?

**Comment by AntyaDev** [comment]
Yes, you are right.
