### ISSUE TITLE
NBomber v5

### ISSUE THREAD

**Issue by AntyaDev** [VIP-Logic/NBomber#587]
- [x] new HTML Report
- [x] add Metrics API (enable/disable)
- [x] remove Response.Latency
- [x] Console message about license
- [x] Add validation on Scenario Name and Step Name to start with a letter
- [ ] Add async NBomberRunner.run or use ConfigureAwaite(false) backgroundResult vs taskResult

**Comment by fabiocbr75** [comment]
Hello,
Is the license changed since version 5?
If I remember well, versions 3 and 4 were usable also for commercial applications with the standalone configuration and only the "enterprise" version was the paid version because there were a lot of specific features like the agent etc...

Can you clarify the license term?

Best Regards,
Fabio

**Comment by AntyaDev** [comment]
Hi @fabiocbr75 ,

You are right. I am preparing a blog post about version 5 and the changes that were introduced. To use NBomber 5 for an organisation you should have a business license: https://www.nuget.org/packages/NBomber/5.0.0/License
