### ISSUE TITLE
NBomber License

### ISSUE THREAD

**Issue by fabiocbr75** [VIP-Logic/NBomber#596]
Hello,
I have some dubs about the license model in a commercial/enterprise environment.

```
- Source code in this repository is licensed under Apache License 2.0
- Since v5, NBomber is licensed under "NBomber Business License 1.1" (https://www.nuget.org/packages/NBomber/5.0.0/License)
- NBomber v5 is FREE ONLY FOR PERSONAL USE. You can't use it for an organization. You need to buy "NBomber Business License".
```

So, NBomber is the assembly produced and saved on Nuget with "NBomber Business License", instead source code on GitHub is Apache 2.
If I use directly the NBomber nuget package I need to have the commercial license, instead, If I compile NBomber from the source code/branch I can continue to use it without the commercial license because is Apache2.
Is it true or also the source code is under "NBomber Business License"?

Best regards,
Fabio

**Comment by AntyaDev** [comment]
Hello @fabiocbr75 
> If I use directly the NBomber nuget package I need to have the commercial license

If you use NBomber v5 you should buy the license. https://www.nuget.org/packages/NBomber/5.0.1/License
If you use NBomber v4 from as a Nuget package - [it's under Apache 2.0](https://www.nuget.org/packages/NBomber/4.1.2/License) 

> If I compile NBomber from the source code/branch I can continue to use it without the commercial license

yes, since the source code on GitHub is for v4 (which is under Apache 2.0) and not for v5.
NBomber v5 is a closed source.

**Comment by fabiocbr75** [comment]
Hello,
Thanks for the clarification.
I didn't understand the source code was aligned with version 4 and not 5. 

Best regards,
Fabio
