### ISSUE TITLE
Feature Request: Provide a way for a scenario to detect that the scenario is ending.

### ISSUE THREAD

**Issue by ctissellb** [VIP-Logic/NBomber#681]
We frequently need to run multiple scenarios simultaneously. Some of these run a continuous loop and need to be able to detect when the primary testing scenario is finished. The request here is to provide a way for Steps to be aware that it's time for the scenario to end.

**Comment by AntyaDev** [comment]
Hi @ctissellb ,

I was thinking about the API for this feature, and I want to keep it as simple as possible.

```csharp
Scenario.Create()
             .WithoutWarmup() 
             .WhenFinish(context => 
             {
                 // here you can call some shared CancellationToken 
                 // to signal other running Scenarios that you finished
                 return Task.Completed
             });
```

What do you think about this?

**Comment by ctissellb** [comment]
Yes, we prioritize simplicity as well. Looks good to me.

**Comment by AntyaDev** [comment]
Hi @ctissellb 
I thought about the feature and API with perspective to keep it simple. I started to think that maybe adding a new handler, `Scenario.WhenFinish`, is not ideal since it may be confused with `Scenario.WithClean`. Instead, I concentrated on providing `CancellationToken` via `IScenarioContext` that can be utilized for several cases. [Here](https://github.com/PragmaticFlow/NBomber/issues/699) I have described this feature. You can leverage `ScenarioCancellationToken` to get a signal that some of your running scenarios are finished. 

You can find this feature in the [latest bet version](https://www.nuget.org/packages/NBomber/5.7.0-beta.7)
Could you please try it out and respond if it will be enough for your use case?

**Comment by AntyaDev** [comment]
Hi @ctissellb 
Are there any updates on this issue?

**Comment by ctissellb** [comment]
Hey @AntyaDev, pardon the delay. I'm just returning from vacation.

Access to the CancellationToken in IScenarioContext meets our needs nicely, thank you!
